"use client"

import { useState } from "react"
import { ShieldCheck, KeyRound, Hash, RefreshCcw } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

async function hmacSha256Hex(keyHex: string, message: string): Promise<string> {
  const keyBytes = new Uint8Array(keyHex.match(/.{1,2}/g)!.map((b) => Number.parseInt(b, 16)))
  const key = await crypto.subtle.importKey("raw", keyBytes, { name: "HMAC", hash: "SHA-256" }, false, ["sign"])
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(message))
  return Array.from(new Uint8Array(sig))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("")
}

export default function ProvablyFairPage() {
  const [serverSeed, setServerSeed] = useState("")
  const [clientSeed, setClientSeed] = useState("default")
  const [txHash, setTxHash] = useState("")
  const [cursor, setCursor] = useState("0")
  const [floatResult, setFloatResult] = useState<string | null>(null)
  const [error, setError] = useState("")

  const [commitment, setCommitment] = useState<{ serverSeedHash: string; activeSince: number } | null>(null)
  const [loadingCommitment, setLoadingCommitment] = useState(false)

  const fetchCommitment = async () => {
    setLoadingCommitment(true)
    try {
      const res = await fetch("/api/fairness")
      const data = await res.json()
      setCommitment({ serverSeedHash: data.serverSeedHash, activeSince: data.activeSince })
    } catch {
      setError("Could not reach the fairness endpoint")
    } finally {
      setLoadingCommitment(false)
    }
  }

  const runVerification = async () => {
    setError("")
    setFloatResult(null)
    if (!/^[0-9a-fA-F]{64}$/.test(serverSeed)) {
      setError("Revealed server seed must be a 64-character hex string")
      return
    }
    try {
      const hex = await hmacSha256Hex(serverSeed, `${clientSeed}:${txHash}:${cursor}`)
      const f = Number.parseInt(hex.slice(0, 8), 16) / 0xffffffff
      setFloatResult(f.toString())
    } catch {
      setError("Failed to compute HMAC — check that the seed is valid hex")
    }
  }

  return (
    <div className="mx-auto max-w-3xl px-4 py-6">
      <div className="fixed inset-0 -z-10 bg-[#0c0b16]" />
      <div className="mb-6 flex items-center gap-3">
        <ShieldCheck className="h-8 w-8 text-emerald-400" />
        <div>
          <h1 className="text-2xl font-bold text-white">Provably Fair</h1>
          <p className="text-sm text-white/60">How Oddiq guarantees every bet is genuinely random and verifiable</p>
        </div>
      </div>

      <div className="space-y-4 rounded-xl border border-white/10 bg-white/5 p-5 text-sm leading-relaxed text-white/70">
        <p>
          Every bet's outcome is derived from{" "}
          <code className="rounded bg-black/40 px-1.5 py-0.5 text-emerald-300">
            HMAC-SHA256(serverSeed, clientSeed:txHash:cursor)
          </code>
          . The <strong className="text-white">server seed</strong> is generated by Oddiq and kept secret; only its
          SHA-256 hash is published up front as a commitment. The{" "}
          <strong className="text-white">client seed</strong> is generated in your browser and stored locally. The{" "}
          <strong className="text-white">txHash</strong> is your own bet transaction hash on Robinhood Chain — unique
          per bet and unknown to anyone until you sign it.
        </p>
        <p>
          Because the commitment is published before your bet exists, and your transaction hash can't be predicted in
          advance, neither Oddiq nor you can bias a result after the fact. When the active server seed is rotated,
          the old one is revealed here so every bet made under it can be independently recomputed and checked.
        </p>
      </div>

      <div className="mt-6 rounded-xl border border-white/10 bg-white/5 p-5">
        <div className="mb-3 flex items-center gap-2">
          <Hash className="h-4 w-4 text-yellow-400" />
          <h2 className="font-bold text-white">Current Commitment</h2>
        </div>
        {commitment ? (
          <div className="space-y-1 font-mono text-xs text-white/70">
            <p className="break-all">serverSeedHash: {commitment.serverSeedHash}</p>
            <p>active since: {new Date(commitment.activeSince).toLocaleString()}</p>
          </div>
        ) : (
          <p className="text-sm text-white/50">Fetch the currently active seed commitment.</p>
        )}
        <Button
          onClick={fetchCommitment}
          disabled={loadingCommitment}
          variant="outline"
          className="mt-3 border-white/20 bg-white/5 text-white hover:bg-white/10"
        >
          <RefreshCcw className="mr-2 h-4 w-4" />
          {loadingCommitment ? "Loading..." : "Fetch Commitment"}
        </Button>
      </div>

      <div className="mt-6 rounded-xl border border-white/10 bg-white/5 p-5">
        <div className="mb-3 flex items-center gap-2">
          <KeyRound className="h-4 w-4 text-yellow-400" />
          <h2 className="font-bold text-white">Verify a Past Bet</h2>
        </div>
        <p className="mb-4 text-xs text-white/50">
          Once a server seed has been revealed (after rotation), paste it below along with your client seed, bet
          txHash, and cursor (0 for most games; dice/plinko use multiple cursors per bet) to recompute the result
          entirely in your browser.
        </p>
        <div className="grid gap-3 sm:grid-cols-2">
          <div>
            <Label className="text-white/60">Revealed Server Seed</Label>
            <Input
              value={serverSeed}
              onChange={(e) => setServerSeed(e.target.value)}
              placeholder="64-char hex"
              className="border-white/10 bg-black/30 text-white"
            />
          </div>
          <div>
            <Label className="text-white/60">Client Seed</Label>
            <Input
              value={clientSeed}
              onChange={(e) => setClientSeed(e.target.value)}
              className="border-white/10 bg-black/30 text-white"
            />
          </div>
          <div>
            <Label className="text-white/60">Bet Transaction Hash</Label>
            <Input
              value={txHash}
              onChange={(e) => setTxHash(e.target.value)}
              placeholder="0x..."
              className="border-white/10 bg-black/30 text-white"
            />
          </div>
          <div>
            <Label className="text-white/60">Cursor</Label>
            <Input
              value={cursor}
              onChange={(e) => setCursor(e.target.value)}
              className="border-white/10 bg-black/30 text-white"
            />
          </div>
        </div>
        <Button onClick={runVerification} className="mt-4 bg-yellow-400 text-black hover:bg-yellow-300">
          Recompute Result
        </Button>
        {floatResult && (
          <p className="mt-3 font-mono text-sm text-emerald-400">Result float [0,1): {floatResult}</p>
        )}
        {error && <p className="mt-3 text-sm text-red-400">{error}</p>}
      </div>
    </div>
  )
}
